baseurl: "https://kau.toke.dk/bufferbloat-archive/"
languageCode: "en-us"
title: "Bufferbloat.net archive"
disable404: true
relativeURLs: false
pluralizeListTitles: false
params:
  author: The Bufferbloat community
