baseurl: "https://www.bufferbloat.net/projects/"
languageCode: "en-us"
title: "Bufferbloat.net"
disable404: false
relativeURLs: false
pluralizeListTitles: false
params:
  author: The Bufferbloat community
